[required_data]
required = ["claim"]

[content]
# static content
instruction_system = """I will review what you said and identify aspects to verify. For each aspect, I will generate a verification question.
My response will begin with 'To verify it:', and each verification question will start with "I googled:" and be listed on a new line."""

exemplar_1_user = "You said: Your nose switches back and forth between nostrils. When you sleep, you switch about every 45 minutes. This is to prevent a buildup of mucus. It’s called the nasal cycle."
exemplar_1_assistant = """To verify it:
1. I googled: Does your nose switch between nostrils?
2. I googled: How often does your nostrils switch?
3. I googled: Why does your nostril switch?
4. I googled: What is nasal cycle?"""

exemplar_2_user = "You said: The Stanford Prison Experiment was conducted in the basement of Encina Hall, Stanford’s psychology building."
exemplar_2_assistant = """To verify it:
1. I googled: Where was Stanford Prison Experiment was conducted?"""

exemplar_3_user = "You said: The Havel-Hakimi algorithm is an algorithm for converting the adjacency matrix of a graph into its adjacency list. It is named after Vaclav Havel and Samih Hakimi."
exemplar_3_assistant = """To verify it:
1. I googled: What does Havel-Hakimi algorithm do?
2. I googled: Who are Havel-Hakimi algorithm named after?"""

exemplar_4_user = """You said: "Time of My Life" is a song by American singer-songwriter Bill Medley from the soundtrack of the 1987 film Dirty Dancing. The song was produced by Michael Lloyd."""
exemplar_4_assistant = """To verify it:
1. I googled: Who sings the song "Time of My Life"?
2. I googled: Which film is the song "Time of My Life" from?
3. I googled: Who produced the song "Time of My Life"""

exemplar_5_user = "You said: Kelvin Hopins was suspended from the Labor Party due to his membership in the Conservative Party."
exemplar_5_assistant = """To verify it:
1. I googled: Why was Kelvin Hopins suspended from Labor Party?"""

exemplar_6_user = "You said: Social work is a profession that is based in the philosophical tradition of humanism. It is an intellectual discipline that has its roots in the 1800s."
exemplar_6_assistant = """To verify it:
1. I googled: What philosophical tradition is social work based on?
2. I googled: What year does social work have its root in?"""

# dynamic content
dynamic = ["prompt_template_user", "prompt_template_assistant"]
# templates
prompt_template_user = """You said: {claim}"""

prompt_template_assistant = """To verify it:
"""

[message_structure]
messages = [
    { "role" = "system", "content" = "instruction_system" },
    { "role" = "user", "content" = "exemplar_1_user" },
    { "role" = "assistant", "content" = "exemplar_1_assistant" },
    { "role" = "user", "content" = "exemplar_2_user" },
    { "role" = "assistant", "content" = "exemplar_2_assistant" },
    { "role" = "user", "content" = "exemplar_3_user" },
    { "role" = "assistant", "content" = "exemplar_3_assistant" },
    { "role" = "user", "content" = "exemplar_4_user" },
    { "role" = "assistant", "content" = "exemplar_4_assistant" },
    { "role" = "user", "content" = "exemplar_5_user" },
    { "role" = "assistant", "content" = "exemplar_5_assistant" },
    { "role" = "user", "content" = "exemplar_6_user" },
    { "role" = "assistant", "content" = "exemplar_6_assistant" },
    { "role" = "user", "content" = "prompt_template_user" },
]
