[required_data]
required = ["claim", "query", "evidence"]

[message_structure]
messages = [
    { "role" = "system", "content" = "instruction_system" },
    { "role" = "user",   "content" = "exemplar_1_user"},
    { "role" = "assistant", "content" = "exemplar_1_assistant"},
    { "role" = "user",   "content" = "exemplar_2_user" },
    { "role" = "assistant", "content" = "exemplar_2_assistant"},
    { "role" = "user",   "content" = "exemplar_3_user"},
    { "role" = "assistant", "content" = "exemplar_3_assistant"},
    { "role" = "user",   "content" = "exemplar_4_user"},
    { "role" = "assistant", "content" = "exemplar_4_assistant"},
    { "role" = "user",   "content" = "exemplar_5_user"},
    { "role" = "assistant", "content" = "exemplar_5_assistant"},
    { "role" = "user",   "content" = "exemplar_6_user"},
    { "role" = "assistant", "content" = "exemplar_6_assistant"},
    { "role" = "user",   "content" = "exemplar_7_user"},
    { "role" = "assistant", "content" = "exemplar_7_assistant"},
    { "role" = "user",   "content" = "exemplar_8_user"},
    { "role" = "assistant", "content" = "exemplar_8_assistant"},
    { "role" = "user",   "content" = "exemplar_9_user"},
    { "role" = "assistant", "content" = "exemplar_9_assistant"},
    { "role" = "user",   "content" = "exemplar_10_user"},
    { "role" = "assistant", "content" = "exemplar_10_assistant"},
    { "role" = "user",   "content" = "prompt_template_user"},
    # { "role" = "assistant", "content" = "prompt_template_assistant"}
]

[content]
# static content
instruction_system = '''I will review your claim and evidence and provide you with my reasoning and conclusion.  Each exchange will consist of five lines:
1. Your claim that I will review.
2. Your question that was used to search for evidence.
3. Your retreived evidence that I will review.
4. My reasoning to justify my conclusion.
5. My conclusion of whether the evidence agrees, disagrees, or is irrelevant to your claim.
I will begin line 4 with "4. Reasoning:" and will note any evidence that contradicts your claim.
I will being line 5 with "5. Conclusion:" followed by "agrees" if the evidence supports the claim, "disagrees" if the evidence contradicts the claim, or "irrelevant" if the evidence is not related to the claim.
'''

exemplar_1_user = '''
1. Claim: Your nose switches back and forth between nostrils. When you sleep, you switch about every 45 minutes. This is to prevent a buildup of mucus. It’s called the nasal cycle.
2. I searched: How often do your nostrils switch?
3. I found this evidence: Although we don’t usually notice it, during the nasal cycle one nostril becomes congested and thus contributes less to airflow, while the other becomes decongested. On average, the congestion pattern switches about every 2 hours, according to a small 2016 study published in the journal PLOS One.
'''
exemplar_1_assistant = '''
4. Reasoning: The article said the nose’s switching time is about every 2 hours, and you said the nose’s switching time is about every 45 minutes.
5. Conclusion: evidence disagrees with claim
'''
exemplar_2_user = '''
1. Claim: The Little House books were written by Laura Ingalls Wilder. The books were published by HarperCollins.
2. I searched: Who published the Little House books?
3. I found this evidence: These are the books that started it all -- the stories that captured the hearts and imaginations of children and young adults worldwide. Written by Laura Ingalls Wilder and published by HarperCollins, these beloved books remain a favorite to this day.
'''
exemplar_2_assistant = '''
4. Reasoning: The article said the Little House books were published by HarperCollins and you said the books were published by HarperCollins.
5. Conclusion: evidence agrees with claim
'''
exemplar_3_user = '''
1. Claim: Real Chance of Love was an American reality TV show. Season 2 of the show was won by Cali, who chose to be with Chance.
2. I searched: Who won season 2 of Real Chance of Love?
3. I found this evidence: Real Chance of Love 2: Back in the Saddle is the second season of the VH1 reality television dating series Real Chance of Love. Ahmad Givens (Real) and Kamal Givens (Chance), former contestants on I Love New York are the central figures.
'''
exemplar_3_assistant = '''
4. Reasoning: The article doesn't answer the question and you said that Cali won season 2 of Real Chance of Love.
5. Conclusion: evidence is irrelevant to claim
'''
exemplar_4_user = '''
1. Claim: The Stanford Prison Experiment was conducted in the basement of Jordan Hall, Stanford’s psychology building.
2. I searched: Where was Stanford Prison Experiment conducted?
3. I found this evidence: Carried out August 15-21, 1971 in the basement of Jordan Hall, the Stanford Prison Experiment set out to examine the psychological effects of authority and powerlessness in a prison environment.
'''
exemplar_4_assistant = '''
4. Reasoning: The article said the Stanford Prison Experiment was conducted in Jordan Hall and you said the Stanford Prison Experiment was conducted in Jordan Hall.
5. Conclusion: evidence agrees with claim
'''
exemplar_5_user = '''
1. Claim: Social work is a profession that is based in the philosophical tradition of humanism. It is an intellectual discipline that has its roots in the 1800s.
2. I searched: When did social work have its roots?
3. I found this evidence: The Emergence and Growth of the Social work Profession. Social work’s roots were planted in the 1880s, when charity organization societies (COS) were created to organize municipal voluntary relief associations and settlement houses were established.
'''
exemplar_5_assistant = '''
4. Reasoning: The article said social work has its roots planted in the 1880s and you said social work has its root in the 1800s.
5. Conclusion: evidence agrees with claim
'''
exemplar_6_user = '''
1. Claim: The Havel-Hakimi algorithm is an algorithm for converting the adjacency matrix of a graph into its adjacency list. It is named after Vaclav Havel and Samih Hakimi.
2. I searched: What is the Havel-Hakimi algorithm?
3. I found this evidence: The Havel-Hakimi algorithm constructs a special solution if a simple graph for the given degree sequence exists, or proves that one cannot find a positive answer. This construction is based on a recursive algorithm. The algorithm was published by Havel (1955), and later by Hakimi (1962).
'''
exemplar_6_assistant = '''
4. Reasoning: The article said the Havel-Hakimi algorithm is for constructing a special solution if a simple graph for the given degree sequence exists and you said the Havel-Hakimi algorithm is for converting the adjacency matrix of a graph.
5. Conclusion: evidence disagrees with claim
'''
exemplar_7_user = '''
1. Claim: "Time of My Life" is a song by American singer-songwriter Bill Medley from the soundtrack of the 1987 film Dirty Dancing. The song was produced by Michael Lloyd.
2. I searched: Who was the producer of "(I’ve Had) The Time of My Life"?
3. I found this evidence: On September 8, 2010, the original demo of this song, along with a remix by producer Michael Lloyd , was released as digital files in an effort to raise money for the Patrick Swayze Pancreas Cancer Resarch Foundation at Stanford University.
'''
exemplar_7_assistant = '''
4. Reasoning: The article said that a demo was produced by Michael Lloyd and you said "Time of My Life" was produced by Michael Lloyd.
5. Conclusion: evidence agrees with claim
'''
exemplar_8_user = '''
1. Claim: Tiger Woods is the only player who has won the most green jackets. He has won four times. The Green Jacket is one of the most coveted prizes in all of golf.
2. I searched: What is the Green Jacket in golf?
3. I found this evidence: The green jacket is a classic, three-button, single-breasted and single-vent, featuring the Augusta National Golf Club logo on the left chest pocket. The logo also appears on the brass buttons.
'''
exemplar_8_assistant = '''
4. Reasoning: The article said the Green Jacket is a classic three-button single-breasted and single-vent and you said the Green Jacket is one of the most coveted prizes in all of golf.
5. Conclusion: evidence is irrelevant to claim
'''
exemplar_9_user = '''
1. Claim: Kelvin Hopins was suspended from the Labor Party because he had allegedly sexually harassed and behaved inappropriately towards a Labour Party activist, Ava Etemadzadeh.
2. I searched: Why was Kelvin Hopins suspeneded from the Labor Party?
3. I found this evidence: A former Labour MP has left the party before an inquiry into sexual harassment allegations against him was able to be concluded, the party has confirmed. Kelvin Hopkins was accused in 2017 of inappropriate physical contact and was suspended by the Labour party pending an investigation.
'''
exemplar_9_assistant = '''
4. Reasoning: The article said Kelvin Hopins was suspended because of inappropriate physical contact and you said that Kelvin Hopins was suspended because he allegedly sexually harassed Ava Etemadzadeh.
5. Conclusion: evidence agrees with claim
'''
exemplar_10_user = '''
1. Claim: In the battles of Lexington and Concord, the British side was led by General Thomas Smith.
2. I searched: Who led the British side in the battle of Lexington and Concord?
3. I found this evidence: Interesting Facts about the Battles of Lexington and Concord. The British were led by Lieutenant Colonel Francis Smith. There were 700 British regulars.
'''
exemplar_10_assistant = '''
4. Reasoning: The article said the British side was led by Lieutenant Colonel Francis Smith and you said the British side was led by General Thomas Smith.
5. Conclusion: evidence agrees with claim
'''

# prompt templates
prompt_template_user = '''
1. Claim: {claim}
2. I searched: {query}
3. I found this evidence: {evidence}
'''

prompt_template_assistant = '''
4. Reasoning:'''

# dynamic content
dynamic = ["prompt_template_user"]







