name: rarr-rep
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11.11
  - datasets=3.2.0
  - faiss=1.9.0
  - jsonlines
  - scipy=1.13.0
  - tqdm

  - pip
  - pip:
      - accelerate==1.3.0
      - pyserini==0.44.0
      - scikit-learn==1.6.1
      - toml
      - torch==2.6.0
      - transformers==4.48.3
      - openai==1.61.1