# mac
# model_cache_dir: "/Users/jjr/.cache/huggingface/hub/"
# linux workstation
# model_cache_dir: "/Users/jjr/.cache/huggingface/hub/"
# bunya hpc
# model_cache_dir: "/scratch/project/neural_ir/cache/hf_models/"

shared:
    model_cache_dir: "/scratch/project/neural_ir/cache/hf_models/"


query_gen:
  input_file: "./input/processed/${DATASET}_input_processed.jsonl"
  output_file: "./output/${DATASET}/${DATASET}_q2.jsonl"
  claim_field: "decon_sentence"
  method: "query-gen"
  model_name: "Llama-3.1-70B"
  temperature: 0.7
  num_rounds: 3
  use_modified_prompt: true
  model_cache_dir: "/scratch/project/neural_ir/cache/hf_models/"

# mac paths
# document_reps_dir: "/Users/jjr/datasets/wikipedia_2023/encodings/*"
# corpus_cache_dir: "/Users/jjr/datasets/wikipedia_2023/corpus/"
# home workstation paths
# document_reps_dir: "/home/jjr/datasets/wikipedia_2023/encodings/*"
# corpus_cache_dir: "/home/jjr/datasets/wikipedia_2023/corpus/"
# bunya hpc
# document_reps_dir: "/scratch/project/neural_ir/katya/IR_encoding/wiki_chunked/corpus/*"
# corpus_cache_dir: "/scratch/project/neural_ir/katya/IR_datasets/wikipedia_2023_chunked/"

evidence_retrieval:
  input_file: "./output/${DATASET}/${DATASET}_q2.jsonl"
  output_file: "./output/${DATASET}/${DATASET}_q2_r1.jsonl"
  model_cache_dir: "/scratch/project/neural_ir/cache/hf_models/"
  document_reps_dir: "/scratch/project/neural_ir/katya/IR_encoding/wiki_chunked/corpus/*"
  corpus_cache_dir: "/scratch/project/neural_ir/katya/IR_datasets/wikipedia_2023_chunked/"
  max_evidence_per_query: 1
  debug: false
  resume: false

agreement:
  input_file: "./output/${DATASET}/${DATASET}_q2_r1.jsonl"
  output_file: "./output/${DATASET}/${DATASET}_q2_r1_a1.jsonl"
  model_cache_dir: "/scratch/project/neural_ir/cache/hf_models/"
  claim_field: "decon_sentence"
  model_name: "Llama-3.1-8B"
  temperature: 0.7
  use_modified_prompt: true

