# mac
# model_cache_dir: "/Users/jjr/.cache/huggingface/hub/"
# linux workstation
# model_cache_dir: "/Users/jjr/.cache/huggingface/hub/"
# bunya hpc
# model_cache_dir: "/scratch/project/neural_ir/cache/hf_models/"

shared:
    model_cache_dir: "/scratch/project/neural_ir/cache/hf_models/"

# q4 is RARR queries using number or wikibib fact queries as a baseline
query_gen:
  input_file: "./input/processed/${DATASET}_input_processed.jsonl"
  output_file: "/scratch/user/uqjros13/RARR/output/${DATASET}/${DATASET}_q1.jsonl"
  claim_field: "decon_sentence"
  model_name: "Llama-3.1-8B"
  method: "query-gen"
  temperature: 0.7
  query_strategy: "rounds"   # fact, rounds, baseline_fact, or baseline_count
  baseline_count_key: None # identifies input data for baseline_count strategy
  baseline_count_offset: None   # only needed for +/- in baseline_count strategy
  num_rounds: 3        # only needed for rounds strategy
  max_attempts: 20        # only needed for baseline strategies
  use_modified_prompt: true
  model_cache_dir: "/scratch/project/neural_ir/cache/hf_models/"

# mac paths
# document_reps_dir: "/Users/jjr/datasets/wikipedia_2023/encodings/*"
# corpus_cache_dir: "/Users/jjr/datasets/wikipedia_2023/corpus/"
# home workstation paths
# document_reps_dir: "/home/jjr/datasets/wikipedia_2023/encodings/*"
# corpus_cache_dir: "/home/jjr/datasets/wikipedia_2023/corpus/"
# bunya hpc
# document_reps_dir: "/scratch/project/neural_ir/katya/IR_encoding/wiki_chunked/corpus/*"
# corpus_cache_dir: "/scratch/project/neural_ir/katya/IR_datasets/wikipedia_2023_chunked/"

evidence_retrieval:
  input_file: "/scratch/user/uqjros13/RARR/output/${DATASET}/${DATASET}_q1.jsonl"
  output_file: "/scratch/user/uqjros13/RARR/output/${DATASET}/${DATASET}_q1_r2.jsonl"
  retrieval_model_name: "jina"
  document_reps_dir: "/scratch/project/neural_ir/jj/datasets/wikipedia_20223_chunked/encodings/jina-embeddings-v2-base-en-2/*"
  corpus_cache_dir: "/scratch/project/neural_ir/katya/IR_datasets/wikipedia_2023_chunked/"
  max_evidence_per_query: 1
  debug: false
  model_cache_dir: "/scratch/project/neural_ir/cache/hf_models/"
  resume: false

agreement:
  input_file: "/scratch/user/uqjros13/RARR/output/${DATASET}/${DATASET}_q1_r2.jsonl"
  output_file: "/scratch/user/uqjros13/RARR/output/${DATASET}/${DATASET}_q1_r2_a1.jsonl"
  claim_field: "decon_sentence"
  model_name: "Llama-3.1-8B"
  temperature: 0.7
  use_modified_prompt: true
  model_cache_dir: "/scratch/project/neural_ir/cache/hf_models/"
  resume: false

